language: erlang
otp_release:
  - 17.0
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir
  - git checkout v1.0.2
  - cd ..
  - make -C elixir
before_script:
  - export PATH="`pwd`/elixir/bin:$PATH"
  - mix deps.get --only test
script: mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
